### ISSUE TITLE
[Bug]: milizeus/img missing violence parental rating images?

### ISSUE THREAD

**Issue by planetrocky** [Kometa-Team/Community-Configs#686]
### Link to File

https://github.com/Kometa-Team/Community-Configs/blob/master/milizeus/rating_imdb_parental.yml

### Version Number

2.1.0

### What branch are you on?

master

### Describe the Bug

Config calls for the four levels of the Parental Violence rating none/mild/moderate/severe, but these images aren't in milizeus/img

Example:

![non_violence_mild](https://github.com/user-attachments/assets/039100df-47fb-4144-a532-7c3498c0fa5c)

``` yaml
  non_violence_none:
    template:
      - name: tmp_rating_imdb
    plex_search:
      all:
        label: "Violence:None"

  non_violence_mild:
    template:
      - name: tmp_rating_imdb
    plex_search:
      all:
        label: "Violence:Mild"

  non_violence_moderate:
    template:
      - name: tmp_rating_imdb
    plex_search:
      all:
        label: "Violence:Moderate"

  non_violence_severe:
    template:
      - name: tmp_rating_imdb
    plex_search:
      all:
        label: "Violence:Severe"
```
